// Generated by typings
// Source: node_modules/sift/index.d.ts
declare module "sift" {
  function sift(query:Object):((value:any, index:number, array:any[]) => boolean)|((value:any) => boolean);
  namespace sift {
  }
  export = sift;
}
